// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.20.0
// source: query.sql

package db

import (
	"context"
)

const createCustomer = `-- name: CreateCustomer :exec
INSERT INTO users(username,password,email,address) VALUES ($1,$2,$3,$4)
`

type CreateCustomerParams struct {
	Username string
	Password string
	Email    string
	Address  []byte
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) error {
	_, err := q.db.Exec(ctx, createCustomer,
		arg.Username,
		arg.Password,
		arg.Email,
		arg.Address,
	)
	return err
}

const getById = `-- name: GetById :one
SELECT id, username, password, email, address FROM users WHERE id = $1 LIMIT 1
`

func (q *Queries) GetById(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getById, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Password,
		&i.Email,
		&i.Address,
	)
	return i, err
}

const getProductsByIds = `-- name: GetProductsByIds :many
SELECT id, name, price, stock FROM products WHERE id = ANY($1::int[])
`

func (q *Queries) GetProductsByIds(ctx context.Context, dollar_1 []int32) ([]Product, error) {
	rows, err := q.db.Query(ctx, getProductsByIds, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.Stock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
